---
name: Update dependent repositories
on:
  push:
    branches:
      - main
jobs:
  update-dependent-repositories:
    uses: networkservicemesh/.github/.github/workflows/update-dependent-repositories-gomod.yaml@main
    with:
      dependent_repositories: |
        ["integration-k8s-gke"]
      base_repository: "networkservicemesh/integration-tests"
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
